<?php
	include_once("fconfig.php");
	if(!isset($_SESSION["admin"])){
		header("Location: admin-022225.php");
	}
	
	$msg = "";
	if(isset($_POST["create"])){
		$name = mysqli_real_escape_string($db_conn, $_POST["name"]);
		$email = mysqli_real_escape_string($db_conn, $_POST["email"]);
		$phone = mysqli_real_escape_string($db_conn, $_POST["phone"]);
		$address = mysqli_real_escape_string($db_conn, $_POST["address"]);
		$lga = mysqli_real_escape_string($db_conn, $_POST["lga"]);
		$photo = $_FILES["photo"]["name"];
		$photo_tmp = $_FILES["photo"]["tmp_name"];
		
		if(!empty($name)
		&& !empty($email)
		&& filter_var($email, FILTER_VALIDATE_EMAIL)
		&& !empty($phone)
		&& strlen($phone) == 11
		&& !empty($address)
		&& !empty($lga)
		&& !empty($photo)){
			$agent_code = strtolower(substr(str_shuffle("QWERTYUIOPASDFGHJKLZXCVBNM1234567890"), 0, 6));
			if(mysqli_num_rows(mysqli_query($db_conn, "SELECT * FROM ".$db_json["agent_table"]." WHERE email='".$email."'")) == 0){
				move_uploaded_file($photo_tmp, "static/agent/".$agent_code.".jpg");
				mysqli_query($db_conn, "INSERT INTO ".$db_json["agent_table"]." (code, fullname, email, phone, address, lga, photo) VALUES ('$agent_code', '$name', '$email', '$phone', '$address', '$lga', '".$agent_code.".jpg')");
				$msg = '<div class="p-2 bg-secondary text-white rounded-1">Registration successful, AGENT CODE: '.strtoupper($lga).'-'.strtoupper($agent_code).'</div>';
			}else{
				$msg = '<div class="p-2 bg-danger text-white rounded-1">Email choosen by another agent!</div>';
			}
		}else{
			$msg = '<div class="p-2 bg-danger text-white rounded-1">Fill all required fields!</div>';
		}
	}
	
	
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>RIFAN | Create Agent</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<style type="text/css">
	
	input::file-selector-button {
		display: none;
	}

</style>
</head>
<body>

<?php include_once("navbar.php"); ?>

<center>
<div id="container" class="col-10">
	
	<h1 class="fs-5 mt-5">AGENT REGISTRATION FORM</h1>
	<?php echo $msg; ?>
	<form method="post" enctype="multipart/form-data">
	
	<div class="input-group input-group mb-3 mt-3">
		<div class="input-group-prepend">
			<span class="input-group-text">Agent Code</span>
		</div>
		<input name="" type="text" class="form-control" placeholder="To be generated by the system" disabled>
	</div>
	
	<div class="input-group input-group mb-3 mt-3">
		<div class="input-group-prepend">
			<span class="input-group-text">Fullname</span>
		</div>
		<input name="name" type="text" class="form-control" required>
	</div>
	
	<div class="input-group mb-3 mt-3">
		<div class="input-group-prepend">
			<span class="input-group-text">Email address</span>
		</div>
		<input name="email" type="email" class="form-control" required>
	</div>
	
	<div class="input-group mb-3 mt-3">
		<div class="input-group-prepend">
			<span class="input-group-text">Phone number</span>
		</div>
		<input name="phone" type="text" pattern="[0-9]{11}" title="Phone number must be 11 digit" class="form-control" required>
	</div>
	
	<div class="input-group mb-3 mt-3">
		<div class="input-group-prepend">
			<span class="input-group-text">Agent's address</span>
		</div>
		<input name="address" type="text" class="form-control" required>
	</div>
	
	<div class="input-group mb-3 mt-3">
		<div class="input-group-prepend">
			<span class="input-group-text">Agent's LGA</span>
		</div>
		<select name="lga" class="form-select" required>
			<option selected disabled>Select LGA</option>
			<?php
				$lga_json = json_decode(file_get_contents("lga.json"), true);
				foreach($lga_json as $key => $value){
					echo '<option value="'.$key.'">'.$value.'</option>';
				}
			?>
		</select>
	</div>
	
	<div class="input-group mb-3 mt-3">
		<div class="input-group-prepend">
			<span class="input-group-text">Upload Agent's Picture</span>
		</div>
		<input name="photo" type="file" class="form-control" required>
	</div>
	
	
	<input type="submit" value="CREATE AGENT" name="create" class="btn btn-secondary col-12">
	</form>
	
</div>
</center>



</body>
</html>