<?php
include_once("fconfig.php");
if (!isset($_SESSION["admin"])) {
	header("Location: admin-022225.php");
}

$search_text = "";
$get_page_search = strip_tags($_GET["search"]);
if (!empty($get_page_search) && strlen($get_page_search) >= 1) {
	$search_text = strtoupper($get_page_search);
}

$exp_search_text = array_filter(explode("-", trim($search_text)));
$agent_code = trim($exp_search_text[1]);
$agent_lga = trim($exp_search_text[0]);
$select_agents = mysqli_query($db_conn, "SELECT * FROM " . $db_json["agent_table"] . " WHERE code = '$agent_code' AND lga = '$agent_lga'");
if (mysqli_num_rows($select_agents) == 1) {
	$get_agent = mysqli_fetch_array($select_agents);
	$msg = '<div class="p-2 bg-secondary text-white rounded-1">Agent Info Retrieved successfully</div>';
} else {
	if (empty($search_text)) {
		$msg = '<div class="p-2 bg-danger text-white rounded-1">Fill all required fields!</div>';
	} else {
		$msg = '<div class="p-2 bg-danger text-white rounded-1">Agent not registered with us</div>';
	}
}

$msg = "";
if (isset($_POST["edit"])) {
	$name = mysqli_real_escape_string($db_conn, $_POST["name"]);
	$email = mysqli_real_escape_string($db_conn, $_POST["email"]);
	$phone = mysqli_real_escape_string($db_conn, $_POST["phone"]);
	$address = mysqli_real_escape_string($db_conn, $_POST["address"]);
	$lga = mysqli_real_escape_string($db_conn, $_POST["lga"]);
	$photo = $_FILES["photo"]["name"];
	$photo_tmp = $_FILES["photo"]["tmp_name"];

	if (
		!empty($name)
		&& !empty($email)
		&& filter_var($email, FILTER_VALIDATE_EMAIL)
		&& !empty($phone)
		&& strlen($phone) == 11
		&& !empty($address)
		&& !empty($lga)
	) {
		if (mysqli_num_rows(mysqli_query($db_conn, "SELECT * FROM " . $db_json["agent_table"] . " WHERE code = '$agent_code' OR email='" . $email . "'")) == 1) {
			if (!empty($photo)) {
				unlink("static/agent/" . $agent_code . ".jpg");
				move_uploaded_file($photo_tmp, "static/agent/" . $agent_code . ".jpg");
			}

			mysqli_query($db_conn, "UPDATE " . $db_json["agent_table"] . " SET fullname='$name', phone='$phone', address='$address', lga='$lga', photo='" . $agent_code . ".jpg' WHERE email='$email'");
			$msg = '<div class="p-2 bg-secondary text-white rounded-1">Update successful, AGENT CODE: ' . strtoupper($lga) . '-' . strtoupper($agent_code) . '</div>';
		} else {
			$msg = '<div class="p-2 bg-danger text-white rounded-1">Agent not exists! or Email might be taken</div>';
		}
	} else {
		$msg = '<div class="p-2 bg-danger text-white rounded-1">Fill all required fields!</div>';
	}
}




?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>RIFAN | Edit Agent</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
		crossorigin="anonymous"></script>
	<style type="text/css">
		input::file-selector-button {
			display: none;
		}
	</style>
</head>

<body>

	<?php include_once("navbar.php"); ?>

	<center>
		<div id="container" class="col-10">
			<?php if (empty($search_text) || mysqli_num_rows($select_agents) !== 1) { ?>
				<h1 class="fs-5 mt-5">ENTER AGENT CODE</h1>
				<?php echo $msg; ?>
				<form method="get">
					<div class="input-group input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Agent Code</span>
						</div>

						<input id="" type="text" name="search" value="<?php echo strtoupper($search_text); ?>"
							class="form-control" required>
						<div class="input-group-append">
							<button type="submit" name="" class="btn btn-secondary">GO</button>
						</div>
					</div>
				</form>
			<?php } else { ?>
				<h1 class="fs-5 mt-5">EDIT AGENT</h1>
				<?php echo $msg; ?>
				<form method="post" enctype="multipart/form-data">

					<div class="input-group input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Agent Code</span>
						</div>
						<input name="" type="text" class="form-control" placeholder="To be generated by the system"
							value="<?php echo $agent_lga . "-" . $agent_code; ?>" disabled>
					</div>

					<div class="input-group input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Fullname</span>
						</div>
						<input name="name" type="text" value="<?php echo $get_agent["fullname"]; ?>" class="form-control"
							required>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Email address</span>
						</div>
						<input name="email" type="email" value="<?php echo $get_agent["email"]; ?>" class="form-control"
							required>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Phone number</span>
						</div>
						<input name="phone" type="text" value="<?php echo $get_agent["phone"]; ?>" pattern="[0-9]{11}"
							title="Phone number must be 11 digit" class="form-control" required>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Agent's address</span>
						</div>
						<input name="address" type="text" value="<?php echo $get_agent["address"]; ?>" class="form-control"
							required>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Agent's LGA</span>
						</div>
						<select name="lga" class="form-select" required>
							<option disabled>Select LGA</option>
							<?php
							$lga_json = json_decode(file_get_contents("lga.json"), true);
							foreach ($lga_json as $key => $value) {
								if ($key == $agent_lga) {
									echo '<option selected value="' . $key . '">' . $value . '</option>';
								} else {
									echo '<option value="' . $key . ' ">' . $value . '</option>';
								}
							}
							?>
						</select>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text"><img
									src="static/agent/<?php echo strtolower($get_agent["photo"]) . "?t=" . rand(); ?>"
									style="width: 100px; height: 100px; object-fit: cover; object-position: center;"
									class="" /></span>
						</div>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Upload Agent's Picture</span>
						</div>
						<input name="photo" type="file" class="form-control">
						<div class="input-group-append">
							<span class="input-group-text">Optional</span>
						</div>
					</div>



					<input type="submit" value="SAVE CHANGES" name="edit" class="btn btn-secondary col-12">
				</form>
			<?php } ?>

		</div>
	</center>



</body>

</html>