<?php
include_once("fconfig.php");
if(!isset($_SESSION["admin"]) && !isset($_SESSION["agent"])){
	header("Location: index.php");
}

$search_text = "";
$get_page_search = strip_tags($_GET["search"]);
if (!empty($get_page_search) && strlen($get_page_search) >= 1) {
	$search_text = strtoupper($get_page_search);
}

$exp_search_text = array_filter(explode("-", trim($search_text)));
$farmer_code = trim($exp_search_text[1]);
$farmer_lga = trim($exp_search_text[0]);
$select_farmers = mysqli_query($db_conn, "SELECT * FROM " . $db_json["farmer_table"] . " WHERE code = '$farmer_code' AND lga = '$farmer_lga'");
if (mysqli_num_rows($select_farmers) == 1 && ((!isset($_SESSION["admin"]) && $farmer_lga == $_SESSION["agent_lga"]) || isset($_SESSION["admin"]))) {
	$get_farmer = mysqli_fetch_array($select_farmers);
	$msg = '<div class="p-2 bg-secondary text-white rounded-1">Farmer Info Retrieved successfully</div>';
} else {
	if (empty($search_text)) {
		$msg = '<div class="p-2 bg-danger text-white rounded-1">Fill all required fields!</div>';
	} else {
		$msg = '<div class="p-2 bg-danger text-white rounded-1">Farmer not registered with us</div>';
	}
}

$msg = "";
if (isset($_POST["edit"])) {
	$name = mysqli_real_escape_string($db_conn, $_POST["name"]);
	$email = mysqli_real_escape_string($db_conn, $_POST["email"]);
	$phone = mysqli_real_escape_string($db_conn, $_POST["phone"]);
	$nin = mysqli_real_escape_string($db_conn, $_POST["nin"]);
	$farm_location = mysqli_real_escape_string($db_conn, $_POST["farm-location"]);
	$address = mysqli_real_escape_string($db_conn, $_POST["address"]);
	$lga = mysqli_real_escape_string($db_conn, $_POST["lga"]);
	$photo = $_FILES["photo"]["name"];
	$photo_tmp = $_FILES["photo"]["tmp_name"];
	
	if(!empty($name)
	&& !empty($email)
	&& filter_var($email, FILTER_VALIDATE_EMAIL)
	&& !empty($phone)
	&& strlen($phone) == 11
	&& !empty($nin)
	&& strlen($nin) == 11
	&& !empty($farm_location)
	&& !empty($address)
	&& !empty($lga)
	&& ((!isset($_SESSION["admin"]) && $lga == $farmer_lga) || isset($_SESSION["admin"]))){
		if (mysqli_num_rows(mysqli_query($db_conn, "SELECT * FROM " . $db_json["farmer_table"] . " WHERE code = '$farmer_code' OR email='" . $email . "'")) == 1) {
			if (!empty($photo)) {
				unlink("static/farmer/" . $farmer_code . ".jpg");
				move_uploaded_file($photo_tmp, "static/farmer/" . $farmer_code . ".jpg");
			}

			mysqli_query($db_conn, "UPDATE " . $db_json["farmer_table"] . " SET fullname='$name', phone='$phone', nin='$nin', farm_location='$farm_location', address='$address', lga='$lga', photo='" . $farmer_code . ".jpg' WHERE email='$email'");
			$msg = '<div class="p-2 bg-secondary text-white rounded-1">Update successful, AGENT CODE: ' . strtoupper($lga) . '-' . strtoupper($farmer_code) . '</div>';
		} else {
			$msg = '<div class="p-2 bg-danger text-white rounded-1">Agent not exists! or Email might be taken</div>';
		}
	} else {
		$msg = '<div class="p-2 bg-danger text-white rounded-1">Fill all required fields!</div>';
	}
}




?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>RIFAN | Edit Farmer</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
		crossorigin="anonymous"></script>
	<style type="text/css">
		input::file-selector-button {
			display: none;
		}
	</style>
</head>

<body>

	<?php include_once("navbar.php"); ?>

	<center>
		<div id="container" class="col-10">
			<?php if (empty($search_text) || mysqli_num_rows($select_farmers) !== 1 || (isset($_SESSION["agent"]) && $farmer_lga !== $_SESSION["agent_lga"])) { ?>
				<h1 class="fs-5 mt-5">ENTER FARMER CODE</h1>
				<?php echo $msg; ?>
				<form method="get">
					<div class="input-group input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Farmer Code</span>
						</div>

						<input id="" type="text" name="search" value="<?php echo strtoupper($search_text); ?>"
							class="form-control" required>
						<div class="input-group-append">
							<button type="submit" name="" class="btn btn-secondary">GO</button>
						</div>
					</div>
				</form>
			<?php } else { ?>
				<h1 class="fs-5 mt-5">EDIT FARMER</h1>
				<?php echo $msg; ?>
				<form method="post" enctype="multipart/form-data">

					<div class="input-group input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Farmer Code</span>
						</div>
						<input name="" type="text" class="form-control" placeholder="To be generated by the system"
							value="<?php echo $farmer_lga . "-" . $farmer_code; ?>" disabled>
					</div>

					<div class="input-group input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Fullname</span>
						</div>
						<input name="name" type="text" value="<?php echo $get_farmer["fullname"]; ?>" class="form-control"
							required>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Email address</span>
						</div>
						<input name="email" type="email" value="<?php echo $get_farmer["email"]; ?>" class="form-control"
							required>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Phone number</span>
						</div>
						<input name="phone" type="text" value="<?php echo $get_farmer["phone"]; ?>" pattern="[0-9]{11}"
							title="Phone number must be 11 digit" class="form-control" required>
					</div>
					
					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">NIN number</span>
						</div>
						<input name="nin" type="text" value="<?php echo $get_farmer["nin"]; ?>" pattern="[0-9]{11}"
							title="NIN must be 11 digit" class="form-control" required>
					</div>
					
					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Farm Location</span>
						</div>
						<input name="farm-location" type="text" value="<?php echo $get_farmer["farm_location"]; ?>" class="form-control"
							required>
					</div>
					
					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Farmer's address</span>
						</div>
						<input name="address" type="text" value="<?php echo $get_farmer["address"]; ?>" class="form-control"
							required>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Agent's LGA</span>
						</div>
						<select name="lga" class="form-select" required>
							<option disabled>Select LGA</option>
							<?php
							$lga_json = json_decode(file_get_contents("lga.json"), true);
							foreach ($lga_json as $key => $value) {
								if ($key == $farmer_lga) {
									echo '<option selected value="' . $key . '">' . $value . '</option>';
								} else {
									if(isset($_SESSION["admin"])){
										echo '<option value="' . $key . ' ">' . $value . '</option>';
									}
								}
							}
							?>
						</select>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text"><img
									src="static/farmer/<?php echo strtolower($get_farmer["photo"]) . "?t=" . rand(); ?>"
									style="width: 100px; height: 100px; object-fit: cover; object-position: center;"
									class="" /></span>
						</div>
					</div>

					<div class="input-group mb-3 mt-3">
						<div class="input-group-prepend">
							<span class="input-group-text">Upload Farmer's Picture</span>
						</div>
						<input name="photo" type="file" class="form-control">
						<div class="input-group-append">
							<span class="input-group-text">Optional</span>
						</div>
					</div>



					<input type="submit" value="SAVE CHANGES" name="edit" class="btn btn-secondary col-12">
				</form>
			<?php } ?>

		</div>
	</center>



</body>

</html>